services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qr-backend
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${APP_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - DB_LOGGING=${DB_LOGGING}
      - DB_SSL=${DB_SSL}
      - FRONTEND_URL=${FRONTEND_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_CEDULA=${ADMIN_CEDULA}
    restart: unless-stopped